### ISSUE TITLE
Testing the plugin.

### ISSUE THREAD

**Issue by paaljoachim** [laneparton/WP-Multisite-Move-Content#1]
Hey Lane @laneparton 

I am testing your plugin.

I am writing a tutorial on various multisite plugins, and I am also hoping to add it to my tutorial.
I see there is no plugin description and perhaps no settings screen yet.

How do we use your plugin?
Thanks!

**Comment by laneparton** [comment]
Hi @paaljoachim 

I appreciate the interest, but I ended up abandoning the idea... I used Broadcast and the NS Cloner plugins to accomplish my needs.

The primary holdup on this plugin was always the WPML relations that I had to support.
